# Generated by Django 6.0.7 on 2026-07-24 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('SG', 'Singapore'), ('MY', 'Malaysia'), ('ID', 'Indonesia'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('PH', 'Philippines'), ('TW', 'Taiwan'), ('BR', 'Brazil')], db_index=True, max_length=2)),
                ('shop_id', models.CharField(db_index=True, max_length=32)),
                ('item_id', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16)),
                ('force', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('json_path', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['region', 'shop_id', 'item_id'], name='products_sc_region_2a2967_idx'), models.Index(fields=['region', 'item_id'], name='products_sc_region_9773d9_idx'), models.Index(fields=['status', 'created_at'], name='products_sc_status_f05e25_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('SG', 'Singapore'), ('MY', 'Malaysia'), ('ID', 'Indonesia'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('PH', 'Philippines'), ('TW', 'Taiwan'), ('BR', 'Brazil')], db_index=True, max_length=2)),
                ('shop_id', models.CharField(db_index=True, max_length=32)),
                ('item_id', models.CharField(db_index=True, max_length=32)),
                ('json_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_records', to='products.scrapejob')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['region', 'shop_id', 'item_id'], name='products_pr_region_5435ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'item_id'), name='uniq_region_item')],
            },
        ),
    ]
